title = 'Rum and Popcorn'
baseURL = 'https://www.rumandpopcorn.com/'
languageCode = 'en-gb'
theme = 'chocos'
timezone = 'Europe/London'

[pagination]
  pagerSize = 5

[params]
  footer_text = 'I live in Leeds. I like film. And food.'
  github_username = 'brokensbone/rumandpopcorn'
  instagram_username = 'edsalkeld'
  date_format = "02 Jan 2006"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
  [outputFormats.PLAINTEXT]
    mediatype = "text/plain"
    isPlainText = true
    notAlternative = true
    baseName = "index"

[permalinks]
    posts = "/:year/:month/:slug"

[frontmatter]
  date  = [":default", ":filename"]

[services.rss]
  limit = 20

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_', '^RUNNER_', '^HOME$', '^USER$', '^PATH$', '^SHELL$', '^LANG$', '^TZ$', '^NODE_', '^GO_']